### ISSUE TITLE
radvd - default getway

### ISSUE THREAD

**Issue by rsftsi** [radvd-project/radvd#118]
I configured a network using radvd.conf in the network gateway, everything it's working well.

**The problem:** When I stop the radvd process the default gateway of all machine is removed instantaneously. When this occur the whole network is not working - all hosts in the network stop. In my point of view this is a big problem that I could not solve yet.

**My question:** Is there some way for the default gateway do not be removed when radvd process is stoped or there is some other issue involving it?  Please could you help me?

I have tried this options, but did not solve the problem.

- AdvRouteLifetime infinity;

- AdvRoutePreference medium;

- RemoveRoute off;

For more details, below the radvd.conf. The daemon version is: 2.17

interface enp0s3 {
        AdvSendAdvert on;
        AdvLinkMTU 1480;
        prefix fd4d:XXXX:XXXX:XXXX:a00:27ff:fe5e:7248/64        {
                DeprecatePrefix on;
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };

        RDNSS 2001:4860:4860::8888 2001:4860:4860::8844 {
        FlushRDNSS off;
        };

        DNSSL t1.com {
        FlushDNSSL off;
        };

        route ::/0 {
        AdvRouteLifetime infinity;
        AdvRoutePreference medium;
        RemoveRoute on;
        };

};

Thanks in advance!

GOD bless you!!!

**Comment by Testsr** [comment]
The  radvd.conf below has  RemoveRoute on. Is this the current config of the gateway?

**Comment by rsftsi** [comment]
Actually this is the actual configuration, but I had tried "RemoveRoute off;" too, but the result is the same.

**Comment by stappersg** [comment]
Closing this stale issue.
