### ISSUE TITLE
New version: 2.19?

### ISSUE THREAD

**Issue by Neustradamus** [radvd-project/radvd#125]
It will be possible to have a new release?

**Comment by reubenhwk** [comment]
Yes. I’ll look over the outstanding pull requests and look at cut a release this week.

**Comment by Neustradamus** [comment]
@reubenhwk: Thanks for the 2.19 version!

But in release section, we see: https://i.ibb.co/wcsyNqR/radvd-2-18rc1.png
- https://github.com/reubenhwk/radvd/releases

Can you add changelog for 2.18 and 2.19?
I think that you can remove the changelog for 2.18rc1 no? (better in 2.18)

And can you do an announcement on ML/website?
- http://www.litech.org/radvd/

Thanks a lot in advance.

**Comment by reubenhwk** [comment]
Yes, I plan to update the website soon.

**Comment by reubenhwk** [comment]
Oh wait I think my last response was meant for a different email thread...
I'll reread this thread later and hopefully respond appropriately.

**Comment by Neustradamus** [comment]
@reubenhwk: Thanks for website but unstable is in highlight here:
- https://github.com/reubenhwk/radvd/releases

And no announcement on ML :/

**Comment by Neustradamus** [comment]
@reubenhwk: Any news for the 2.19 announcement?

Always 2.18 RC1 instead of 2.18 here:
- https://github.com/reubenhwk/radvd/releases

And no 2.19 here:
- http://lists.litech.org/listinfo/radvd-announce-l
- http://lists.litech.org/listinfo/radvd-devel-l

Thanks in advance.

**Comment by stappersg** [comment]
Thanks for the new release and the announce emails.

Thing I miss is http://v6web.litech.org/radvd/dist/radvd-2.19.tar.xz.asc  There is http://v6web.litech.org/radvd/dist/radvd-2.17.tar.xz.asc and http://v6web.litech.org/radvd/dist/radvd-2.18.tar.xz.asc

Will there be a `radvd-2.19.tar.xz.asc` ?
```
stappers@paddy:~/src/debianpackaging/radvd
$ uscan
uscan: Newest version of radvd on remote site is 2.19, local version is 2.18
uscan:  => Newer package available from
        => http://v6web.litech.org/radvd/dist/radvd-2.19.tar.xz
uscan warn: In directory ., downloading
  http://v6web.litech.org/radvd/dist/radvd-2.19.tar.xz.asc failed: 404 Not Found
uscan die: FAIL Checking OpenPGP signature (no signature file downloaded).
stappers@paddy:~/src/debianpackaging/radvd
$ 
```

**Comment by stappersg** [comment]
Ah, I just did see #129.  That issue expresses better what I'm missing.

**Comment by Neustradamus** [comment]
I think it is needed to have a perfect 1.20 soon.
- With last PRs

With a perfect announcement at the same time:
- Mailing lists
- Official website
- Releases section (always not done for 2.18 and 2.19) : https://github.com/reubenhwk/radvd/releases
- Signature

**Comment by Neustradamus** [comment]
@vp1981 @anthraxx @stappersg: @reubenhwk has generated signatures:
- https://github.com/radvd-project/radvd/releases/tag/v2.19

**Comment by Neustradamus** [comment]
@vp1981 @anthraxx @stappersg: @robbat2 has done new signatures:
- https://github.com/radvd-project/radvd/releases/tag/v2.19

**Comment by Neustradamus** [comment]
@vp1981 @anthraxx @foxxx0, @stappersg: @robbat2 has done new signatures:
- https://github.com/radvd-project/radvd/releases/tag/v2.19

**Comment by Neustradamus** [comment]
@reubenhwk has done it.
