### ISSUE TITLE
Expired https certificate since 2013

### ISSUE THREAD

**Issue by Neustradamus** [radvd-project/radvd#128]
There is a problem with HTTPS:
- https://www.litech.org/radvd/

Expired certificate since 2013.

https://litech.org/radvd/ does not work.

Note : It is better to have a default website without www.
- https://dropwww.com/why

**Comment by reubenhwk** [comment]
I'd like to drop the whole website and just let it all be hosted on
Github.  I'm not an admin at litech.  It'd be easier for me to move away
from it... It's just that that url and site has been maintained there for
well over a decade. I'm considering making one final update to the website
to point anybody to the Github project for future releases...

**Comment by reubenhwk** [comment]
Also I love this: https://dropwww.com/why

Reminds me of the story about the woman who always cut the fish to fit a
pan lost long ago by her grandmother....because that's the way she always
did it.

**Comment by robbat2** [comment]
https://radvd.litech.org/ is now powered by GitHub sites and has valid HTTPS cert.

**Comment by Neustradamus** [comment]
@robbat2: I had forgotten this issue ^^
