### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by reubenhwk** [radvd-project/radvd#135]
I'm ready to retire...

**Comment by stappersg** [comment]
FWIW [https://github.com/reubenhwk/radvd/issues/135](https://github.com/reubenhwk/radvd/issues/135)
links to [https://github.com/radvd-project/radvd/issues/135](https://github.com/radvd-project/radvd/issues/135)

Actual
```
FWIW [https://github.com/reubenhwk/radvd/issues/135](https://github.com/reubenhwk/radvd/issues/135)
links to [https://github.com/radvd-project/radvd/issues/135](https://github.com/radvd-project/radvd/issues/135)
```

In other words: some kind of rename did happen ...

**Comment by Neustradamus** [comment]
After the announcement, the radvd repositories have moved from:
- https://github.com/reubenhwk/radvd to https://github.com/radvd-project/radvd
- https://github.com/reubenhwk/radvdweb to https://github.com/radvd-project/radvdweb

**Comment by robbat2** [comment]
@reubenhwk Can you try to do some manner of handoff here visibly, so that @stappersg and others can see your intent. Since we had some extensive discussions via email, we need to followup more publicly.

**Comment by reubenhwk** [comment]
Yes, I'm handing off radvd to robbat2, who's been a co-maintainer for some while now.  I've moved the radvd project from my personal github account to the radvd-project account.  My original gpg key is gone so there will be no signature to verify the move.

**Comment by stappersg** [comment]
The handover did happen.

**Comment by robbat2** [comment]
Closing this issue now :-)
