### ISSUE TITLE
Add automated build support.

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [radvd-project/radvd#137]
Hi everyone,

I could try to add automated build using GitHub Actions, so each repository push and each pull request are automatically checked against a bunch of supported operating systems.
I can currently add Linux, Solaris (I don't know if this one is relevant) and (maybe) FreeBSD builds. I can also add the same matrix build that I made for [PPP](https://github.com/paulusmack/ppp), so a pull request can be checked against several libc (uClibc, musl, glibc) on various architectures through Buildroot.

What do you think about ?

PS : thank you @Neustradamus for suggesting this !

**Comment by stappersg** [comment]
On Sat, Jan 23, 2021 at 01:48:03PM -0800, Adrien RICCIARDI wrote:
> 
> What do you think about ?
> 

Patches welcome

**Comment by stappersg** [comment]
> Patches welcome

I think that became #139.  If so, is this issue obsolete.

**Comment by RICCIARDI-Adrien** [comment]
Do you want to add Fedora or OpenSUSE Linux distributions CIs ?

**Comment by stappersg** [comment]
On Tue, Mar 30, 2021 at 11:14:47AM -0700, Adrien RICCIARDI wrote:
> Do you want to add Fedora or OpenSUSE Linux distributions CIs ?
> 

All patches will be reviewed.


And the future will show what CI did bring the radvd project.

**Comment by robbat2** [comment]
I believe this task has been completed, and further work is just in expanding the matrix, so the issue can be closed.
