### ISSUE TITLE
How do I set radvd to ignore my ISP DNS?

### ISSUE THREAD

**Issue by Vista2003** [radvd-project/radvd#142]
I have radvd running on my EdgeRouter X and since Ubiquiti has been unhelpful, I thought that bringing it here might lead me closer to the answer.  I have a Pi-hole that I want it to use as a DNS server, I've figured out a stop-gap measure that if I would edit the radvd.conf file and restart the service it would change it but only temporarily until something reverts it back to using the ISP DNS server.
```
interface switch0 {
  This section was automatically generated by the Vyatta configuration sub-system.  Do not edit it.
   service type [slaac]

    IgnoreIfMissing on;
    AdvSendAdvert on;
    RDNSS 2a02:8010:1:0:212:23:3:100  { };
    AdvManagedFlag off;
    AdvOtherConfigFlag off;
    prefix ::/64 {
          AdvOnLink on;
          AdvAutonomous on;
    };
};
```

This is the config file when it's using the ISP servers and as a stopgap, I would edit the RDNSS address to my own. I know there is probably a better way, I just haven't figured it out. 

(note: edited by maintainer for markdown syntax only)

**Comment by stappersg** [comment]
> I just haven't figured it out.

And what will be your next step?

**Comment by ThinkPadX220** [comment]
Asking here was my next step and trying out whatever is suggested here

**Comment by robbat2** [comment]
Here's what I use on my UBNT ERPro8 (running v2.0.x firmware) successfully:
```
set interfaces ethernet eth0 ipv6 router-advert name-server 'fdXX:...'
```
And that address points to an `unbound` DNS server elsewhere on my network.

Give that a try, and it should generate RDNSS entries

You should go and poke around in the files of `vyatta-ipv6-rtradv` on the EdgeRouters to drive radvd better

**Comment by stappersg** [comment]
Thank you @robbat2 

> and trying out whatever is suggested here

I look forward to the feedback.

**Comment by ThinkPadX220** [comment]
> Here's what I use on my UBNT ERPro8 (running v2.0.x firmware) successfully:
> 
> ```
> set interfaces ethernet eth0 ipv6 router-advert name-server 'fdXX:...'
> ```
> 
> And that address points to an `unbound` DNS server elsewhere on my network.
> 
> Give that a try, and it should generate RDNSS entries
> 
> You should go and poke around in the files of `vyatta-ipv6-rtradv` on the EdgeRouters to drive radvd better

I've tried putting that command into both eth0 and ppoe0 to no effect :(
I'll have a poke around vyatta-ipv6-rtradv now

**Comment by stappersg** [comment]
@Vista2003  Please provide us with at least one reason why this issue should remain open.

**Comment by Vista2003** [comment]
> You should go and poke around in the files of vyatta-ipv6-rtradv on the EdgeRouters to drive radvd better
I've had a poke around and can't find anything relating to DNS, could you give me some pointers?

> @Vista2003 Please provide us with at least one reason why this issue should remain open.
It's up to you if you want to close it or not since this is starting to get out of the scope of radvd

**Comment by robbat2** [comment]
Inside `vyatta-ipv6-rtradv` is this script: `/opt/vyatta/sbin/vyatta_gen_radvd.pl`
Look for `name-server`, which has at least this block:
```perl
    # Process Name Servers 
    my @nameservers = $config->returnValues("$param_root name-server");
    log_msg("nameservers = @nameservers\n");
    if (@nameservers) {
        print $FD_WR "    RDNSS ";
        foreach my $nameserver (@nameservers) {
            print $FD_WR "$nameserver ";
        }       
        print $FD_WR "{\n    };\n";  
    }
```

If that file doesn't contain these lines at all, then I'm not sure what UBNT is doing differently on your hardware, since I'm running on the ERPro8 and you are on the X line.

**Comment by robbat2** [comment]
I'd say further questions in this thread probably belong on UBNT's forums.
