### ISSUE TITLE
musl-libc: segfault when link-local address is listed as a client

### ISSUE THREAD

**Issue by jsarenik** [radvd-project/radvd#158]
According to suggestion in [#157](https://github.com/radvd-project/radvd/issues/157#issuecomment-830859620) I am making this fresh issue. This issue is related to [musl-libc](https://www.musl-libc.org/)-only.

A minimal config file example:

```
interface eth0
{
   AdvSendAdvert on;
   prefix 2001:470:1f1b:365::/64
   {
     AdvOnLink on;
     AdvAutonomous on;
   };
   clients
   {
     fe80::aa20:66ff:fe3f:1909; # this is radvd server's link-local,
     # forgotten when the config was re-used from another host
     # though on glibc-based system it does not cause segfault
   };
};
```

The config file contains the link-local address of current host by error. It was forgotten there when the config file was transferred from another host that previously run `radvd`.

This is what happens:

```
# radvd -n -C /etc/radvd.conf -d5 -m stderr_clean
version 2.19 started
eth0 interface definition ok
config file, /etc/radvd.conf, syntax ok
...
eth0 linklocal address: fe80::aa20:66ff:fe3f:1909
eth0 address: OTHERADDRESS
eth0 address: fe80::aa20:66ff:fe3f:1909
eth0 is ready
sending RA to fe80::aa20:66ff:fe3f:1909 on eth0 (fe80::aa20:66ff:fe3f:1909), 3 options (using 64/1210 bytes)
eth0 next scheduled RA in 16 second(s)
polling for 16 second(s), next iface is eth0
Exiting, privsep_read_loop had readn return 0 bytes
Exiting, privsep_read_loop is complete.
Segmentation fault
```

**Comment by robbat2** [comment]
Can do a debug build, and put that coredump through gdb for a backtrace?

**Comment by jsarenik** [comment]
@robbat2 Yes. I will wrte here as soon as it is ready.

**Comment by jsarenik** [comment]
@robbat2 Oops, do I need any options when running `./configure`? So far I see only addresses in the core:

```
# gdb --core=core.10985 --batch                                    
[New LWP 10985]
Core was generated by `/usr/local/sbin/radvd -n -C /etc/radvd.conf -d5 -m stderr_clean'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1ea3b10edb in ?? ()
```

And it is current HEAD (b368cb9) compiled with `-g` (default).

**Comment by jsarenik** [comment]
$ file /usr/local/sbin/radvd
    /usr/local/sbin/radvd: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped

**Comment by richfelker** [comment]
From the backtrace, this is obviously the result of calling a function without a declataion, which would have been caught with `-Werror=implicit-function-declaration`. The invalid pointer is a pointer that has been truncated to 32 bits with the upper bit sign-extended to 64 bits. So it looks like you're missing `#include <net/if.h>`.

And indeed, here is your bug:

https://github.com/radvd-project/radvd/blob/b368cb98da5da44154994de573fea24b7c7858fc/includes.h#L79-L84

It's explicitly doing the wrong thing on linux that's not glibc.

**Comment by richfelker** [comment]
I can't find anything in the tracker about why the above wrong change was made, so to fix this you'll probably have to figure out what prompted that and solve it the right way. Ping me if it's not clear what to do and I'll be happy to look at it.

**Comment by rpodgorny** [comment]
well, following the "git blame" leads to commit 46883f8a1a02fe42040dd8e48aec0ed871545d4d which has comment:

Allow building on musl
Signed-off-by: Matthew Thode <mthode@mthode.org>

**Comment by rpodgorny** [comment]
so it seems matthew made it compile on musl but did not test it thoroughly during actual runtime...

**Comment by jpds** [comment]
I just patched out those if/else lines on my gentoo/musl install, left `#include <net/if.h>` in place and it compiled and starts up fine.

Will see if radvd segfaults in the coming days.

**Comment by robbat2** [comment]
@prometheanfire ^^ this was your musl change, can you review and submit alternate options?
