### ISSUE TITLE
Is it possible to delegate an ipv6-prefix with radvd?

### ISSUE THREAD

**Issue by deep-42-thought** [radvd-project/radvd#159]
I get a /48 prefix from upstream dhcp6, of which I advertise two /64 prefixes on downstream interfaces via radvd. Now, I'd like to delegate another /64 (or anything between /48 and /64) prefix to one client on one of those interfaces. Is that possible with radvd? I seem unable to find any documentation on how to delegate a whole prefix somewhere.

**Comment by stappersg** [comment]
FWIW:  I don't understand the request

Advice: Rewrite the request in other words

**Comment by deep-42-thought** [comment]
Ok, I'll elaborate a little more (skip all the details, which you don't want to know):

My router "archlix" runs radvd to advertise X:Y:Z:1::/64 and X:Y:Z:2::/64 subnets on enp0s11 (ethernet/lan) and wlp0s12 (wifi) respectively. The whole X:Y:Z::/48 is routed to archlix from my IPv6 tunnel broker (on some other interface).
Now, I have an openWRT router "buoy", which connects on wlp0s12, gets a proper IPv6 address within X:Y:Z:2::/64 and is configured to "Request IPv6-prefix of length 64" (words of "luci", the web frontend of openWRT).
Buoy's request for a whole prefix delegation, obviously is not satisfied by archlix, because it has no clue, what prefix should be given to buoy. I would like to delegate the X:Y:Z:3::/64 (or any other X:Y:Z:W::/64 for W>=3) to buoy. It would be ok for me, if radvd only advertised the prefix to buoy, but did not actually put the proper routing rules in place - I can do this manually / by some hand-crafted script.

My question: Can I use radvd to handle this scenario? Or should I be looking for a different tool, here?

**Comment by stappersg** [comment]
Closing this _help me to design my network_.

**Comment by deep-42-thought** [comment]
There seems to be some misunderstanding here:
I'm not asking how to design my network, I'm asking, if some feature (prefix delegation) is possible with radvd.

**Comment by mcr** [comment]
deep-42-thought ***@***.***> wrote:
    > Is that possible with radvd? I seem unable to
    > find any documentation on how to delegate a whole prefix somewhere.

No, you need a dhcpv6-PD server.  It's not in the RA protocol, alas.
