### ISSUE TITLE
radvd refuse to run when using dynamic user

### ISSUE THREAD

**Issue by NeverBehave** [radvd-project/radvd#165]
When using systemd with dynamic user, radvd will generate the following logs:

```
radvd (60509): version 2.19 started
radvd (60509): exiting, permissions on conf_file invalid
```

It is believed to be cause by https://github.com/radvd-project/radvd/blob/bc34bf790c7441d75a1168abdf29eeeb4e87c18c/radvd.c#L871 where `getpwnam` will not find related entry

Related: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=

> The user and group will not be added to /etc/passwd or /etc/group, but are managed transiently during runtime.

**Comment by stappersg** [comment]
On Sun, Jan 02, 2022 at 01:21:19AM -0800, NeverBehave wrote:
> radvd (60509): exiting, permissions on conf_file invalid

Gutfeeling:
  that "error" is reproducable for any non-priviledge user,
  it is unrelated to dynamic user

**Comment by robbat2** [comment]
What systemd script is this? 

`-u` needs to be passed as a existant username used to drop privileges to. e.g. `nobody`

We could potentially modify it to optionally take `uid:gid` of numeric values to drop to rather than a named user.

**Comment by robbat2** [comment]
https://github.com/radvd-project/radvd/pull/166 fixes a related case, but still need info on how this is being used badly with systemd.

**Comment by stappersg** [comment]
@NeverBehave Please share the  _systemd unit file you are using_ with this issue.

**Comment by NeverBehave** [comment]
In our previous setup, we set up root user and `-u radvd` to start the service. However, when we switch to our new setup, where radvd is started with low-privileged user, we forget to remove that from the ExecStart. We have tested that radvd works when starting directly under unprivileged user. I have attached the script as reference:

```
[Service]
Environment="LOCALE_ARCHIVE=/nix/store/imsdp94kfmdj2hwfgzh0pxxln3nhbm4c-glibc-locales-2.33-56/lib/locale/locale-archive"
Environment="PATH=/nix/store/l6f4z8mmcnnxba8w004xn28y0vr4gdkf-coreutils-9.0/bin:/nix/store/v3lvq9hqshyldc4i6f5jy0zs0k5psbws-findutils-4.8.0/bin:/nix/store/nkwls56wcfwi1r0jnkqkvwx2zk7w3qrz-gnugrep-3.7/bin:/nix/store/vklvyr82ajbz7jm7g8dbkh62k20b0dpr-gnused-4.8/bin:/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/bin:/nix/store/l6f4z8mmcnnxba8w004xn28y0vr4gdkf-coreutils-9.0/sbin:/nix/store/v3lvq9hqshyldc4i6f5jy0zs0k5psbws-findutils-4.8.0/sbin:/nix/store/nkwls56wcfwi1r0jnkqkvwx2zk7w3qrz-gnugrep-3.7/sbin:/nix/store/vklvyr82ajbz7jm7g8dbkh62k20b0dpr-gnused-4.8/sbin:/nix/store/aqwqh3drn9bf6qrs70wiyrxaawh1wcnz-systemd-249.5/sbin"
Environment="TZDIR=/nix/store/7wxhajvlpndhmcwrpc73sl959yb7jzbr-tzdata-2021c/share/zoneinfo"


AmbientCapabilities=CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_RAW
CapabilityBoundingSet=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_RAW
DynamicUser=yes
ExecStart=/nix/store/hp9h8rcac62clx3bnn9r001pm297lkpv-radvd-2.19/bin/radvd -n -p /run/xyz/radvd.pid -C xxx.cfg
RuntimeDirectory=xxx-srv-radvd
User=xxx-srv-radvd
 ```

This is not a problem with radvd, and thanks for taking time for this :)

**Comment by robbat2** [comment]
@NeverBehave Can we talk about how to be more meaningful there? `radvd` only needs some of those capabilities to start up, and then doesn't need them afterwards. Right now it implicitly drops caps when it does setuid, but in your case it won't end up dropping caps.

**Comment by zhaofengli** [comment]
Am I understanding it correctly that radvd currently cannot drop capabilities with `capset`, only through `setuid`? It would mean that we have to launch it as root, allocate a global user for it to drop privileges to, and trust that it does drop the capabilities correctly.

**Comment by robbat2** [comment]
Yes, the code today doesn't use capabilities directly, only implicitly via setuid, specifically the details under `capabilities(7)`, sub-section `Effect of user ID changes on capabilities`
