### ISSUE TITLE
Specify source address for client

### ISSUE THREAD

**Issue by zhihuiyuze** [radvd-project/radvd#175]
Hi, there
   Is there any way to specify the source address for clients? Such as `from 2a0c:e640:101a::/64 via fe80::36f7:16ff:fec4:4e13 dev enp3s0`?

**Comment by stappersg** [comment]
Please elaborate.

**Comment by robbat2** [comment]
If you're talking about the fe80::/64 selection, that decision is made entirely client side.

`radvd` cannot influence it.
Clients may have valid cases for using multiple link-local addresses, e.g. MAC rotation privacy, or CGA/SEND per RFC3972 & RFC3971.

Does that sufficiently answer your question?

**Comment by zhihuiyuze** [comment]
Well, this is not the thing that I mean.
 
 I mean to advertise a 2 segment prefix, let the first segment go through GW1 and the second segment go through GW2.
 For example from 240e::/64 via GW2 and from 2a0c::1 via GW2.

I looked at the radvd example and it seems that RA can't do this? Maybe DHCPv6 can?

**Comment by mcr** [comment]
RA can't do this. Nor can DHCPv6.
Each GW must advertise the prefixes they expect to forward.

**Comment by robbat2** [comment]
I don't quite follow what you mean.
Do you mean that you want to have two different prefixes on the same physical L2 segment, each with a different gateway?
Or just next-hop routes?

Either way, you need to run `radvd` on EACH of those gateways. That's the one thing you can't get around. RA protocol doesn't let you inject arbitrary routes that would go via another device.

In the config for GW1 & GW2, depending what you mean, it could be either `prefix 240e::/64` & `prefix 2a0c::/64`; or just `route 240e::/64` and `route 2a0c::/64`

**Comment by zhihuiyuze** [comment]
Hi,
   I mean like this. I can't control the DHCPv6 server on TP-LINK, and I want to let the source address 240e::/64 go to TP-LINK 
2a0c::/64 go to Linux router. but there are in the same physical L2 segment,

![1](https://user-images.githubusercontent.com/38281461/161389249-01bd2906-445a-4431-9162-e6900619ef02.png)
 
yes, I want prefix 240e::/6 and prefix 2a0c::/6 to have different next-hop

**Comment by robbat2** [comment]
Sorry, this isn't a `radvd` limitation, but the nature of the RouterAdv protocol itself.

You MUST have two daemons/services running there, one on each Router, advertising the blocks you want from the respective router.

If the PC is the only thing that needs it, I'd suggest static route configuration on the PC instead of using RouterAdv.
