### ISSUE TITLE
Issue when radvd advertises the routes

### ISSUE THREAD

**Issue by dpounraj** [radvd-project/radvd#191]
I have radvd running on my device which has MIPS arch.
versions : kernel 3.4.11-rt19 , radvd 1.8.5.

radvd is advertising /64 network to LAN clients.

The device also has to accept RA (IP address and default route) in routing mode on WAN side.
So, updated flags as below
/proc/sys/net/ipv6/conf/bdg1/accept_ra = 2 
/proc/sys/net/ipv6/conf/bdg1/autoconf = 1

We make use of bdg interfaces by binding physical ports to it.
Here bdg2 is bind with physical LAN port eth3 and eth3.0 
	 bdg1 is bind with eth0.X (X = VLAN number)
All IPs are assigned to bdg interfaces.

Issue: When radvd advertises the routes in interface bdg2, it is received/accepted by bdg1 and a stateless IPv6 address is added to the interface as below.

Question :
1) Can we restrict learning of routes advertised by one interface to another interface of the same device?
2) Is the config of radvd correct?
 
Find the radvd configurations below,

interface bdg2
 {
        AdvSendAdvert on;
        AdvManagedFlag on; # bdg2-AdvManagedFlag-place-holder
        AdvOtherConfigFlag off; # bdg2-AdvOtherConfigFlag-place-holder
        prefix 2006:db8:110f:ee76::/64
        {
                AdvOnLink on;
                AdvValidLifetime 2592000;
                AdvPreferredLifetime 604800;
                AdvAutonomous on; # bdg2-AdvAutonomous-place-holder
        };
        RDNSS 2001::54 {  }; # place holder 0
        # place holder 1
        # place holder 2
        # place holder 3
};  # bdg2-end-block

#ip -6 route
2006:db8:110f:ee76::/64 dev bdg1  proto kernel  metric 256  expires 2146765sec
2006:db8:110f:ee76::/64 dev bdg2  proto kernel  metric 256
#

#ifconfig bdg1
bdg1      Link encap:Ethernet  HWaddr xx:xx:B0:FD:EE:77
          inet addr:192.168.49.1  Bcast:192.168.29.255  Mask:255.255.255.0
          inet6 addr: 2006:db8:110f:ee76:1277:b0ff:fefd:ee77/64 Scope:Global
          inet6 addr: fe80::1277:b0ff:fefd:ee77/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3966 errors:0 dropped:70 overruns:0 frame:0
          TX packets:2286 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:264237 (258.0 KiB)  TX bytes:575615 (562.1 KiB)

Note: We cannot update to the latest version of radvd due to some constraints.

**Comment by stappersg** [comment]
On Wed, Oct 05, 2022 at 03:16:24AM -0700, BlackHacker wrote:
>  I have radvd running on my device which has MIPS arch.
> versions : kernel 3.4.11-rt19 , radvd 1.8.5.
> 

Seeing the 1.8.5 version number made me
check https://github.com/radvd-project/radvd/tags

Then after about six pages further
did https://github.com/radvd-project/radvd/tags?after=v1.9.6
tell me that  v1.8.5 is from the year 2012.

**Comment by stappersg** [comment]
> Note: We cannot update to the latest version of radvd due to some constraints.

Which means:  _There is no reason to keep this issue open._
