### ISSUE TITLE
radvd only sends a router lifetime of 0

### ISSUE THREAD

**Issue by Colum31** [radvd-project/radvd#206]
Hello,

with my config:

```
interface ipoe.666 
{
	
    AdvDefaultLifetime 1800;
    MaxRtrAdvInterval 60;
    MinRtrAdvInterval 30;
    AdvSendAdvert on;
    AdvRASolicitedUnicast on;
	
    AdvSendAdvert on;
    AdvManagedFlag on;
    AdvOtherConfigFlag on;

    prefix 2001:db8:1234:8000::/64
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
};
```
all RA have a router lifetime of 0. It does not matter which values I plug into `AdvDefaultLifetime`.

Is this a bug or am I missing something?

I have built radvd from source:

Version: 2.19

Compiled in settings:
  default config file		"/etc/radvd.conf"
  default pidfile		"/var/run/radvd.pid"
  default logfile		"/var/log/radvd.log"
  default syslog facility	24

**Comment by robbat2** [comment]
Can you please include the output of `ip -6 addr` (mask out the first 4-6 octets of your non-fe80 addresses for privacy.

Also, are you sure that /proc/sys/net/ipv6/conf/all/forwarding or per-interface variable is enabled?

**Comment by robbat2** [comment]
Cannot reproduce. I suspect your system may have a dynamic address with a lower lifetime, causing what you observed.

Using your config, minor tweaks to dummy0 & `2001:db8::/64`:

```
tcpdump: listening on dummy0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
e2:6a:7a:f5:2c:42 > 33:33:00:00:00:01, ethertype IPv6 (0x86dd), length 110: (flowlabel 0x417d0, hlim 255, next-header ICMPv6 (58) payload length: 56) fe80::e06a:7aff:fef5:2c42 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 56
	hop limit 64, Flags [managed, other stateful], pref medium, router lifetime 1800s, reachable time 0ms, retrans timer 0ms
	   prefix info option (3), length 32 (4): 2001:db8::/64, Flags [onlink], valid time 86400s, pref. time 14400s
	     0x0000:  4080 0001 5180 0000 3840 0000 0000 2001
	     0x0010:  0db8 0000 0000 0000 0000 0000 0000
	   source link-address option (1), length 8 (1): e2:6a:7a:f5:2c:42
	     0x0000:  e26a 7af5 2c42
```
