### ISSUE TITLE
Add the possibility to disable DNS

### ISSUE THREAD

**Issue by Palando** [radvd-project/radvd#209]
Can you please implement the possibility to disable the advertisment of DNS servers?

I want to use a special DNS server that does only support IPv4 for now and therefore I would like to disable the IPv6 DNS server. On the host that runs radvd I would like to have an IPv6 DNS server. The problem is, radvd uses the IPv6 DNS server if it is configured in the resolv.conf file. So can anybody please implement the the possibility to explicitly disable the RDNSS?

**Comment by robbat2** [comment]
Can you please share the configuration?

The way `radvd` is written, if the configuration does NOT include RDNSS settings, it shouldn't pick them up at all.
`radvd` does NOT read `resolv.conf` at all.


Example as a minimal RA packet, containing only a prefix and nothing else:
```
10:07:39.696456 IP6 (flowlabel 0xc2bd3, hlim 255, next-header ICMPv6 (58) payload length: 48) fe80::e06a:7aff:fef5:2c42 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 48
	hop limit 64, Flags [managed, other stateful], pref medium, router lifetime 1800s, reachable time 10000ms, retrans timer 5000ms
	  prefix info option (3), length 32 (4): fd3c:b2e8:93df:f::/64, Flags [onlink, auto], valid time 300s, pref. time 60s
	    0x0000:  40c0 0000 012c 0000 003c 0000 0000 fd3c
	    0x0010:  b2e8 93df 000f 0000 0000 0000 0000
```

**Comment by Neustradamus** [comment]
@Palando: Can you look the @robbat2 comment?

**Comment by stappersg** [comment]
Do know that a closed issue can allows additional comments.
