### ISSUE TITLE
Improve Buildroot CI

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [radvd-project/radvd#214]
Hi all,

I would like to improve the Buildroot GitHub CI as I did for the PPP project (@Neustradamus).
The goal is to provide prebuit Buildroot images to the radvd CI, so only radvd needs to be compiled instead of the whole Buildroot images. With these improvements, all the Buildroot tests (all architectures + all C libraries) take about 4 minutes to run in PPP.

If you are OK with that, I would need a dedicated repo with push access, for instance `radvd-ci`, to generate and store the Buildroot images (see https://github.com/ppp-project/ppp-ci for the PPP equivalent).

**Comment by stappersg** [comment]
> would need a dedicated repo with push access, for instance `radvd-ci`

Fine with me.   And it would be available I had the privilege to create it.

![image](https://github.com/radvd-project/radvd/assets/35434094/59f38018-3155-401e-9776-da28c3783baa)

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Done like PPP, thanks in advance :)
Thanks to @stappersg for the answer!

**Comment by RICCIARDI-Adrien** [comment]
Thanks to both of you !

**Comment by robbat2** [comment]
@RICCIARDI-Adrien  is there any specific reason that other repo must be private? I'd strongly prefer it to be public, to aid verification.

**Comment by RICCIARDI-Adrien** [comment]
Not at all ! It can be switched to public right now.

**Comment by RICCIARDI-Adrien** [comment]
Indeed, can someone with enough permissions switch the repo to public ? I need this to be able to continue running GitHub Actions (I spent all the minutes allowed to a private repo). Maybe @Neustradamus ?

**Comment by robbat2** [comment]
I see it's switched now

**Comment by RICCIARDI-Adrien** [comment]
Thank you !
