### ISSUE TITLE
Support blank config files

### ISSUE THREAD

**Issue by audreylace** [radvd-project/radvd#224]
I found it odd that radvd considers blank files to be invalid. Main use case for empty files is to allow other services in the system to simply write changes to the configuration file and simply tell radvd reload. Right now they can do this but it requires re-starting radvd as the process quits out. 

Suggested changes, do know this would require fixing the [poll bug.](https://github.com/radvd-project/radvd/pull/223) 

Sample changes:
https://github.com/radvd-project/radvd/compare/master...audreylace:radvd-stinput:support-blank-conffile?expand=1

**Comment by robbat2** [comment]
Agree on the bug; not sure about your branch, it still exits if the file is empty?

**Comment by Neustradamus** [comment]
@audreylace: Have you seen @robbat2 comment?
