### ISSUE TITLE
Question: radvd.conf for GUA via SLAAC and ULA via DHCPv6 

### ISSUE THREAD

**Issue by Django-BOfH** [radvd-project/radvd#231]
Question: I have a router (VM) here that isolates the intranet (IPv6 only) from a DMZ. A radvd is running on the firewall/router. I would now like to assign the GUA in my IPv6 only intranet network via SLAAC, BUT the ULA statically from a DHCPv6 daemon (kea-dhcp6). For DHCP, the AdvManagedFlag must be set to "on" and AdvAutonomouse to "off". For SLAAC, both values are the other way around. But now I have the problem that the parameter AdvManagedFlag is defined for the interface and AdvAutonomous for the prefix, and defining the same interface eth1 twice fails with a radvd -c with an error. :/ 

Now the question arises, how can I configure the radvd so that the GUA can be assigned via SLAAC but the ULA statically via DHCPv6?

**Comment by stappersg** [comment]
13:36 < django> ohh o.k. I see: IRC discussion is intended to cover development issues, and is not intended as a general support system. So I'll search the right place to ask 'bout support!
13:36 < django> pardon ... :/

**Comment by Django-BOfH** [comment]
I have now found a way to get the radvd and kea-dhcp6 to assign the ULA statically by the kea-dhcp6 daemon on the basis of DUIDs, and to have the client negotiate the GUA dynamically via SLAAC.

I have summarized what I did there and how it works in a BLOG post:
https://dokuwiki.nausch.org/doku.php/linux:radvd#musterkonfiguration_gua_via_slaac_und_ula_via_dhcpv6
