### ISSUE TITLE
CI Linux fails, due failed test,  ./test.log not available

### ISSUE THREAD

**Issue by stappersg** [radvd-project/radvd#236]
Upon visiting https://github.com/radvd-project/radvd/actions
and clicking on failed Linux build job there is:
```text
FAIL: check_all
============================================================================
Testsuite summary for radvd 2.20_rc1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
```
That `./test-suite.log` is **not** available as build artifact.

So this issue reporting two issues:
* Failed test
* Logfile `test-suite.log` not available.

**Comment by melroy89** [comment]
Regarding the `test-suite.log` not available as build artifact. Is because you don't upload any artifact.

https://github.com/actions/upload-artifact

You could combine this `upload-artifact` action with `if: always()` to ensure this step is always executed, even if the previous step failed.

**Comment by stappersg** [comment]
There is now merge request #237

**Comment by stappersg** [comment]
Closing this in favor of #237
