### ISSUE TITLE
separate config file prefix list from advert prefix list

### ISSUE THREAD

**Issue by reubenhwk** [radvd-project/radvd#39]
The way RADVD works now, all the prefixes that can be sent are generated from the config file parser when the config file is parsed.  This is a problem with some type of automatic prefix is selected, ::/64, Base6Interface, Base6to4Interface.

The problem is when that interface comes up, radvd doesn't know to check new prefixes on that interface unless it reparses the config file.

What need to be done is to migrate logic from the parser into the send_ra code.

**Comment by jaredmauch** [comment]
Is someone still looking at this issue?

**Comment by reubenhwk** [comment]
No.  Looks like I gave it some thought and never did it.

**Comment by reubenhwk** [comment]
There's a related wrong-prefix branch.  It seems related.

**Comment by reubenhwk** [comment]
I dumped the wrong-prefix branch because it was too old and I didn't like the code anyway.  I'm going to make another attempt at this...

**Comment by Neustradamus** [comment]
Any news?
