### ISSUE TITLE
Multiple configuration files support.

### ISSUE THREAD

**Issue by bukepo** [radvd-project/radvd#73]
Sometimes we need autogenerated some configurations, which are going to be combined with user defined ones. However, it seems very hard to do this job under the current implementation, mainly two restrictions,

1. Currently all configurations are put into a single file.
2. The structured configuration file disallows duplicating interface definitions.

With the restriction 1, it is not easy to separate different configurations, autogenerated or user defined.
With the restriction 2, one interface's configuration must be defined in one place and no modifications or additions are possible with simple file concatenations, nor can priority based configuration be implemented.

So is there any plan to make some changes on these restrictions? I may contribute some code if this is in your plan.

**Comment by reubenhwk** [comment]
There no plan to do that, but it sounds like a useful thing to add.

What values do you want to auto generate?

Could you use something like m4 to do what you need to do now?

**Comment by reubenhwk** [comment]
Yep, tell me more about the autogeneration. We'll need to be very security conscious about anything which is feeding config to radvd.

For 1 & 2, that's very doable. It'll require a lot of flex/bison coding.

**Comment by bukepo** [comment]
Thanks. autogeneration includes some route information. For example, there are 2 interfaces, eth0 and eth1. eth1 is connected to a dynamic network whose prefix may change. I need the route information of eth1 to be advertised on eth0, so that hosts connected to eth0 can access hosts connected to eth1.

**Comment by stappersg** [comment]
After more than three years of silence.
