### ISSUE TITLE
radvd crashes when ifa_addr is NULL in send.c:293

### ISSUE THREAD

**Issue by PlasmaHH** [radvd-project/radvd#79]
According to the getifaddrs manpage ifa_addr can be NULL, which it is on my system, which causes a crash upon send.c:293  if (ifa->ifa_addr->sa_family != AF_INET6)

**Comment by reubenhwk** [comment]
Can you fix it and send a pull request?

**Comment by robbat2** [comment]
A partial patch for it: https://github.com/robbat2/radvd/commit/a459621fac4e8259c43211a9f27d81d60ec33fbc
It looks like there might be the same issue w/ `ifa_netmask`.

**Comment by robbat2** [comment]
@PlasmaHH  can you test that commit?

**Comment by robbat2** [comment]
Reping for getting that tested

**Comment by robbat2** [comment]
@landgraf can you test this one maybe?

**Comment by robbat2** [comment]
This was fixed in
https://github.com/radvd-project/radvd/pull/113
After no responses to test requests
